from .BackgroundWidget import BackgroundEditor
from .event.EventWidget import EventEditor
from .sound_bank.SoundBankWidget import SoundBankEditor
from gui.editors.place.PlaceWidget import PlaceEditor
from gui.editors.puzzle.PuzzleWidget import PuzzleEditor
from .ScriptWidget import ScriptEditor
from .TextWidget import TextEditor
from .sprite.SpriteWidget import SpriteEditor
from .SoundProfileWidget import SoundProfileEditor
from .TimeDefinitionsWidget import TimeDefinitionsEditor
