from .BackgroundWidget import BackgroundEditor
from .event.EventWidget import EventEditor
from .sound_bank.SoundBankWidget import SoundBankEditor
from gui.editors.place.PlaceWidget import PlaceEditor
from gui.editors.puzzle.PuzzleWidget import PuzzleEditor
from .ScriptWidget import ScriptEditor
from .TextWidget import TextEditor
from .sprite.SpriteWidget import SpriteEditor
from .SoundFixWidget import SoundFixEditor
from .TimeDefinitionsWidget import TimeDefinitionsEditor
from .MovieWidget import MovieEditor
from .stream.StreamWidget import StreamEditor
